baseURL = "https://brave-ride-4d3713.netlify.com/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Template Note"

[params]
  author = "Studio Colibri"
  description = "We create unique Notebooks & Notepads using only excess paper"

disableKinds = ["taxonomy", "taxonomyTerm"]
