backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "static/assets/uploads"
public_folder: "/"

collections:
  - name: "shop" # Used in routes, e.g., /admin/collections/blog
    label: "Carnets" # Used in the UI
    folder: "content/shop" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Lien URL", name: "slug", widget: "string"}
      - {label: "Image", name: "img", widget: "image"}
      - {label: "Prix", name: "price", widget: "number", valueType: "int"}
      - {label: "Couleur", name: "color", widget: "string"}
      - {label: "Format", name: "size", widget: "string"}
      - {label: "Nbr de pages", name: "pages", widget: "number", valueType: "int"}
      - {label: "Type de papier", name: "paper", widget: "string"}
      - {label: "Motif", name: "pattern", widget: "string"}
      - {label: "Reliure", name: "binding", widget: "string"}
      - {label: "Imprimeur", name: "print", widget: "string", required: false}
      - {label: "Tags", name: "tags", widget: "list", allow_add: true, required: false }
      - {label: "Mis en avant ?", name: "featured", widget: "select", options: ["non", "oui"] }
      - {label: "Description", name: "body", widget: "markdown"}

  - label: "Pages"
    name: "pages"
    files:
      - label: "About Page"
        name: "about"
        file: "data/about.json"
        fields:
          - label: Block 01
            name: block01
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Description, name: description, widget: markdown}
              - {label: Image, name: img, widget: image}
          - label: Block 02
            name: block02
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Description, name: description, widget: markdown}
              - {label: Image, name: img, widget: image}
          - label: Block 03
            name: block03
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Description, name: description, widget: markdown}
              - {label: Image, name: img, widget: image}
      - label: "Test"
        name: "test"
        file: "data/test.json"
        fields:
          - label: Blocks
            name: blocks
            widget: list
            fields:
              - label: Block
                name: block
                widget: object
                fields:
                  - {label: Title, name: title, widget: string}
                  - {label: Description, name: description, widget: markdown}
                  - {label: Image, name: img, widget: image}
              
